[project]
name = "xindata-income-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "kagglehub>=0.3.12",
    "torch>=2.7.0",
    "transformers>=4.52.4",
]
