
BLOCK_SIZE: int = 1024
NUM_TRAIN_EPOCHS: int = 3
PER_DEVICE_TRAIN_BATCH_SIZE: int = 4
SAVE_STEPS: int = 5000
SAVE_TOTAL_LIMIT: int = 2
LOGGING_STEPS: int = 500
LEARNING_RATE: float = 5e-5
WEIGHT_DECAY: float = 0.01
WARMUP_STEPS: int = 500
EVALUATION_STRATEGY: str = "no"
FP16: bool = True